server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    driver: mysql
    source: root:linkmax@tcp(139.9.196.165:3306)/kingmax_dev?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8mb4
    active: 10
    idle: 5
  redis:
    addr: 127.0.0.1:6379
    auth: "123"
    active: 10
    idle: 5
    readTimeout: 0.2s
    writeTimeout: 0.2s
